name: quiz_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  dotted_border: 2.0.0+3
  custom_radio_grouped_button: 2.1.2+2
  flutter_screenutil: 5.6.0
  lottie: 2.0.0
  firebase_core: 2.2.0
  flutter: 
    sdk: flutter
  firebase_auth: ^4.1.2

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/lottie/
  uses-material-design: true

