// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA7Ki4g78bxXPdlVVHM-foTbedI78GIHA',
    appId: '1:235146380243:web:04d42381260ec172816526',
    messagingSenderId: '235146380243',
    projectId: 'quiz-fe5a3',
    authDomain: 'quiz-fe5a3.firebaseapp.com',
    storageBucket: 'quiz-fe5a3.appspot.com',
    measurementId: 'G-NTK77CQC3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOmb0YQ2LvGS2n4_4n3BGGqGIpVopssjo',
    appId: '1:235146380243:android:36808158c1413f5c816526',
    messagingSenderId: '235146380243',
    projectId: 'quiz-fe5a3',
    storageBucket: 'quiz-fe5a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBle7le3DfK-e05CnwkF8caMvxnGyC2Gs8',
    appId: '1:235146380243:ios:550c25f318d86078816526',
    messagingSenderId: '235146380243',
    projectId: 'quiz-fe5a3',
    storageBucket: 'quiz-fe5a3.appspot.com',
    iosClientId: '235146380243-odehbfcv6heecdglgn97jhesm7je8ha0.apps.googleusercontent.com',
    iosBundleId: 'com.syntax04ro.quizFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBle7le3DfK-e05CnwkF8caMvxnGyC2Gs8',
    appId: '1:235146380243:ios:550c25f318d86078816526',
    messagingSenderId: '235146380243',
    projectId: 'quiz-fe5a3',
    storageBucket: 'quiz-fe5a3.appspot.com',
    iosClientId: '235146380243-odehbfcv6heecdglgn97jhesm7je8ha0.apps.googleusercontent.com',
    iosBundleId: 'com.syntax04ro.quizFlutter',
  );
}
